import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

# Local Test Parameters
INDEX_TRACK_POINT_VOXEL = 67
INDEX_TRAJECTORY = 30
NUM_POINTS_POINT_CLOUD = 450
INDEX_TRACK_POINT_TORUS = 1529
TRAJECTORY_LENGTH_TORUS = 50
