import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

# Local Test Parameters
INDEX_TRACK_POINT_VOXEL = 67
INDEX_TRAJECTORY_VOXEL = 30
BATCH_SIZE_VOXEL = 32
NUM_POINTS_POINT_CLOUD = 2000

INDEX_TRACK_POINT_TORUS = 1529
TRAJECTORY_LENGTH_TORUS = 3500
CAMERA_COORDINATES_TORUS = [0.3, 0.9, -1]
BATCH_SIZE_TORUS = 32
